package git

import (
	"bufio"
	"container/list"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

// ErrExists is returned when creating a repository whose directory
// already exists.
var ErrExists = errors.New("repository already exists")

// Temporary directory prefixes under the store root. A repository is
// created under a temporary name and renamed into place, and deleted by
// renaming it aside first, so a half-created or half-deleted repository
// never appears under its real path. Sweep removes anything left over
// from a crash.
const (
	tmpPrefix   = ".tmp-"
	trashPrefix = ".trash-"
)

// Store is the directory of bare repositories, one per repository ID, and
// the shared object reader pool and object cache used to read them.
type Store struct {
	root  string
	pool  *readerPool
	cache *objectCache
}

// NewStore returns a Store rooted at root. Call Close to stop its readers.
func NewStore(root string) *Store {
	return &Store{
		root: root,
		// 64 readers: comfortably above the concurrency this process
		// actually sees in practice (page requests plus one worker's
		// pipeline fetches), without keeping an unbounded number of git
		// processes idle. 2 minutes: long enough that a reader survives
		// the gap between two requests to the same repository, short
		// enough that an idle repository's readers are eventually reaped.
		pool: newReaderPool(64, 2*time.Minute),
		// Shared across every concurrent reader in the process, unlike
		// OpenHookRepo's much smaller one, which serves a single push.
		cache: newObjectCache(64 << 20),
	}
}

// Close stops every object reader the store started.
func (s *Store) Close() {
	s.pool.close()
}

var repoIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9-]{0,63}$`)

// RepoPath returns where the repository with the given ID lives under
// root. IDs are generated by Gitman, never taken from a request, but the
// pattern check still keeps a malformed ID from ever resolving outside
// root.
func RepoPath(root, repoID string) (string, error) {
	if !repoIDPattern.MatchString(repoID) {
		return "", fmt.Errorf("invalid repository ID %q", repoID)
	}
	return filepath.Join(root, repoID+".git"), nil
}

// Path returns the on-disk path for a repository ID.
func (s *Store) Path(repoID string) (string, error) {
	return RepoPath(s.root, repoID)
}

// Open returns the repository with the given ID. It fails with
// ErrNotFound when the repository directory does not exist.
func (s *Store) Open(repoID string) (*Repo, error) {
	path, err := s.Path(repoID)
	if err != nil {
		return nil, err
	}
	info, err := os.Stat(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("open repository: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("open repository: %s is not a directory", path)
	}
	return &Repo{path: path, source: pooledSource{pool: s.pool, path: path}, cache: s.cache}, nil
}

// Create initializes an empty bare repository whose HEAD names
// defaultBranch.
func (s *Store) Create(ctx context.Context, repoID, defaultBranch string) error {
	path, err := s.Path(repoID)
	if err != nil {
		return err
	}
	if err := ValidateName(defaultBranch); err != nil {
		return fmt.Errorf("default branch: %w", err)
	}
	if LooksLikeCommitHash(defaultBranch) {
		return fmt.Errorf("default branch %q looks like a commit hash", defaultBranch)
	}
	if err := os.MkdirAll(s.root, 0o750); err != nil {
		return fmt.Errorf("create repository root: %w", err)
	}
	if _, err := os.Stat(path); err == nil {
		return ErrExists
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("check repository path: %w", err)
	}

	tmp := filepath.Join(s.root, tmpPrefix+repoID+"-"+randomSuffix())
	defer func() { _ = os.RemoveAll(tmp) }()

	if _, err := run(ctx, cmdOptions{dir: s.root}, "init", "--bare", "--quiet", "--initial-branch="+defaultBranch, tmp); err != nil {
		return fmt.Errorf("initialize repository: %w", err)
	}
	// Reflogs in a bare repository record every ref movement, so a branch
	// that was force-pushed or deleted by mistake can be recovered by an
	// operator.
	if _, err := run(ctx, cmdOptions{dir: tmp}, "config", "core.logAllRefUpdates", "always"); err != nil {
		return fmt.Errorf("configure repository: %w", err)
	}
	// Hooks are supplied per invocation through core.hooksPath; the
	// sample hooks git init copies in are never used, so they are not
	// kept around to suggest otherwise.
	if err := os.RemoveAll(filepath.Join(tmp, "hooks")); err != nil {
		return fmt.Errorf("remove sample hooks: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		if errors.Is(err, fs.ErrExist) {
			return ErrExists
		}
		return fmt.Errorf("move repository into place: %w", err)
	}
	return nil
}

// Delete removes a repository. It first renames the directory aside, so
// the repository disappears atomically even if removing its files is
// interrupted.
func (s *Store) Delete(repoID string) error {
	path, err := s.Path(repoID)
	if err != nil {
		return err
	}
	trash := filepath.Join(s.root, trashPrefix+repoID+"-"+randomSuffix())
	if err := os.Rename(path, trash); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return ErrNotFound
		}
		return fmt.Errorf("move repository aside: %w", err)
	}
	if err := os.RemoveAll(trash); err != nil {
		return fmt.Errorf("remove repository files: %w", err)
	}
	return nil
}

// Sweep removes directories left behind by a Create or Delete that was
// interrupted by a crash. It is meant to run once at startup, before any
// Create is in flight.
func (s *Store) Sweep(ctx context.Context) error {
	entries, err := os.ReadDir(s.root)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read repository root: %w", err)
	}
	var errs []error
	for _, entry := range entries {
		name := entry.Name()
		if strings.HasPrefix(name, tmpPrefix) || strings.HasPrefix(name, trashPrefix) {
			key := strings.TrimPrefix(strings.TrimPrefix(name, tmpPrefix), trashPrefix)
			if i := strings.LastIndexByte(key, '-'); i > 0 && len(key)-i-1 == 12 {
				key = key[:i]
			}
			check, stop := context.WithTimeout(ctx, 50*time.Millisecond)
			unlock, err := s.MutationLock(check, key)
			stop()
			if err != nil {
				continue
			}
			if err := os.RemoveAll(filepath.Join(s.root, name)); err != nil {
				errs = append(errs, err)
			}
			unlock()
		}
	}
	return errors.Join(errs...)
}

func randomSuffix() string {
	var b [6]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("%x", time.Now().UnixNano())
	}
	return hex.EncodeToString(b[:])
}

// objectInfo is the header cat-file prints for an object.
type objectInfo struct {
	hash string
	typ  ObjectType
	size int64
}

// errReaderBroken marks a reader whose pipe is no longer in a known
// state; it is discarded and a fresh one started on next use.
var errReaderBroken = errors.New("object reader is no longer usable")

// reader is one long-lived `git cat-file --batch-command` process for one
// repository. It answers object lookups over a pipe instead of starting a
// new git process for each one. A reader serves one request at a time.
type reader struct {
	mu       sync.Mutex
	cmd      *exec.Cmd
	stdin    io.WriteCloser
	stdout   *bufio.Reader
	broken   bool
	closed   bool
	lastUsed time.Time
}

func startReader(repoPath string, env []string) (*reader, error) {
	cmd := exec.Command("git", "cat-file", "--batch-command")
	cmd.Dir = repoPath
	cmd.Env = append(append(baseEnv(), "GIT_DIR="+repoPath), env...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, fmt.Errorf("start object reader: %w", err)
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		_ = stdin.Close()
		return nil, fmt.Errorf("start object reader: %w", err)
	}
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start object reader: %w", err)
	}
	return &reader{
		cmd:      cmd,
		stdin:    stdin,
		stdout:   bufio.NewReaderSize(stdout, readBufferSize),
		lastUsed: time.Now(),
	}, nil
}

// close stops the reader's process. It is safe to call more than once;
// callers hold r.mu.
func (r *reader) close() {
	r.broken = true
	if r.closed {
		return
	}
	r.closed = true
	_ = r.stdin.Close()
	if r.cmd.Process != nil {
		_ = r.cmd.Process.Kill()
	}
	_ = r.cmd.Wait()
}

// do runs op against the reader. If ctx ends while op is blocked on the
// pipe, the process is killed to unblock it and the reader is marked
// broken, since the pipe's position is then unknown.
func (r *reader) do(ctx context.Context, op func() error) error {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := ctx.Err(); err != nil {
		return err
	}
	if r.broken {
		return errReaderBroken
	}
	stop := context.AfterFunc(ctx, func() {
		if r.cmd.Process != nil {
			_ = r.cmd.Process.Kill()
		}
	})
	err := op()
	killed := !stop()
	r.lastUsed = time.Now()
	if killed {
		r.broken = true
		return ctx.Err()
	}
	if err != nil && !errors.Is(err, ErrNotFound) && !isTooLarge(err) {
		r.broken = true
	}
	return err
}

func isTooLarge(err error) bool {
	var tl *TooLargeError
	return errors.As(err, &tl)
}

// validObjectName guards the newline-delimited "info <name>"/"contents
// <name>" protocol this package speaks to git's batch-command reader: a
// name is written on its own line, so one containing a newline would be
// read as more than one command, and one containing NUL cannot be a
// valid revision or path at all. 4096, PATH_MAX on Linux, bounds it to
// what a real path (the common shape of name, e.g. "HEAD:some/path")
// could plausibly be, past which it is malformed on its way in.
func validObjectName(name string) error {
	if name == "" || len(name) > 4096 || strings.ContainsAny(name, "\n\x00") {
		return fmt.Errorf("invalid object name")
	}
	return nil
}

// readHeader reads one cat-file header line: "<hash> <type> <size>", or
// "<name> missing" / "<name> ambiguous".
func (r *reader) readHeader() (objectInfo, error) {
	line, err := r.stdout.ReadString('\n')
	if err != nil {
		return objectInfo{}, fmt.Errorf("read object header: %w", err)
	}
	line = strings.TrimSuffix(line, "\n")
	if strings.HasSuffix(line, " missing") || strings.HasSuffix(line, " ambiguous") {
		return objectInfo{}, ErrNotFound
	}
	fields := strings.Fields(line)
	if len(fields) != 3 {
		return objectInfo{}, fmt.Errorf("unexpected object header %q", line)
	}
	size, err := strconv.ParseInt(fields[2], 10, 64)
	if err != nil {
		return objectInfo{}, fmt.Errorf("unexpected object size in %q", line)
	}
	return objectInfo{hash: fields[0], typ: ObjectType(fields[1]), size: size}, nil
}

func (r *reader) info(ctx context.Context, name string) (objectInfo, error) {
	if err := validObjectName(name); err != nil {
		return objectInfo{}, err
	}
	var info objectInfo
	err := r.do(ctx, func() error {
		if _, err := io.WriteString(r.stdin, "info "+name+"\n"); err != nil {
			return fmt.Errorf("write object request: %w", err)
		}
		var err error
		info, err = r.readHeader()
		return err
	})
	return info, err
}

// contents reads an object's content, refusing, without reading it, an
// object larger than max.
func (r *reader) contents(ctx context.Context, name string, max int64) (objectInfo, []byte, error) {
	info, err := r.info(ctx, name)
	if err != nil {
		return objectInfo{}, nil, err
	}
	if info.size > max {
		return info, nil, &TooLargeError{Size: info.size}
	}
	var data []byte
	err = r.do(ctx, func() error {
		if _, err := io.WriteString(r.stdin, "contents "+info.hash+"\n"); err != nil {
			return fmt.Errorf("write object request: %w", err)
		}
		header, err := r.readHeader()
		if err != nil {
			return err
		}
		if header.size != info.size {
			return fmt.Errorf("object %s changed size between requests", info.hash)
		}
		data = make([]byte, header.size+1)
		if _, err := io.ReadFull(r.stdout, data); err != nil {
			return fmt.Errorf("read object %s: %w", info.hash, err)
		}
		if data[header.size] != '\n' {
			return fmt.Errorf("object %s: missing trailing newline", info.hash)
		}
		data = data[:header.size]
		return nil
	})
	return info, data, err
}

// objectSource hands out a reader for the duration of one operation.
type objectSource interface {
	with(ctx context.Context, fn func(*reader) error) error
}

// readerPool keeps at most one reader per repository, closes readers that
// have sat idle, and caps how many exist at once. Each reader is used by
// one request at a time; requests for the same repository queue on that
// reader's lock.
type readerPool struct {
	mu      sync.Mutex
	readers map[string]*reader
	max     int
	idle    time.Duration
	done    chan struct{}
	changed chan struct{}
	closed  bool
}

var errPoolClosed = errors.New("object reader pool is closed")

func newReaderPool(max int, idle time.Duration) *readerPool {
	p := &readerPool{readers: make(map[string]*reader), max: max, idle: idle, done: make(chan struct{}), changed: make(chan struct{})}
	go p.reapLoop()
	return p
}

func (p *readerPool) reapLoop() {
	ticker := time.NewTicker(p.idle / 2)
	defer ticker.Stop()
	for {
		select {
		case <-p.done:
			return
		case <-ticker.C:
			p.mu.Lock()
			p.closeIdleLocked(time.Now().Add(-p.idle), 0)
			p.mu.Unlock()
		}
	}
}

// closeIdleLocked closes readers last used before cutoff, stopping once at
// most keep remain when keep > 0. A reader in use holds its own lock, so
// TryLock skips it instead of waiting on a request in flight.
func (p *readerPool) closeIdleLocked(cutoff time.Time, keep int) {
	for path, r := range p.readers {
		if keep > 0 && len(p.readers) <= keep {
			return
		}
		if !r.mu.TryLock() {
			continue
		}
		if r.broken || r.lastUsed.Before(cutoff) {
			r.close()
			delete(p.readers, path)
		}
		r.mu.Unlock()
	}
}

// acquire reserves one reader without exceeding the process limit. Waiting
// for either a busy repository or capacity is cancellable. Creation occurs
// under the pool lock so concurrent requests never spawn duplicate readers.
func (p *readerPool) acquire(ctx context.Context, path string) (*reader, error) {
	for {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		p.mu.Lock()
		if p.closed {
			p.mu.Unlock()
			return nil, errPoolClosed
		}
		if r := p.readers[path]; r != nil {
			if r.mu.TryLock() {
				if !r.broken {
					p.mu.Unlock()
					return r, nil
				}
				r.close()
				delete(p.readers, path)
				r.mu.Unlock()
			} else {
				changed := p.changed
				p.mu.Unlock()
				select {
				case <-ctx.Done():
					return nil, ctx.Err()
				case <-changed:
				}
				continue
			}
		}
		// Evict one idle reader when full; busy readers retain their slot.
		if len(p.readers) >= p.max {
			for other, r := range p.readers {
				if r.mu.TryLock() {
					r.close()
					delete(p.readers, other)
					r.mu.Unlock()
					break
				}
			}
		}
		if len(p.readers) < p.max {
			r, err := startReader(path, nil)
			if err == nil {
				r.mu.Lock()
				p.readers[path] = r
			}
			p.mu.Unlock()
			return r, err
		}
		changed := p.changed
		p.mu.Unlock()
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-changed:
		}
	}
}

func (p *readerPool) signalLocked() {
	close(p.changed)
	p.changed = make(chan struct{})
}

// forget removes r from the pool if it is still registered and closes it.
func (p *readerPool) forget(path string, r *reader) {
	p.mu.Lock()
	if p.readers[path] == r {
		delete(p.readers, path)
		p.signalLocked()
	}
	p.mu.Unlock()
	r.mu.Lock()
	r.close()
	r.mu.Unlock()
}

func (p *readerPool) release(path string, r *reader) {
	broken := r.broken
	r.mu.Unlock()
	if broken {
		p.forget(path, r)
	}
	p.mu.Lock()
	p.signalLocked()
	p.mu.Unlock()
}

func (p *readerPool) close() {
	p.mu.Lock()
	if p.closed {
		p.mu.Unlock()
		return
	}
	p.closed = true
	close(p.done)
	p.signalLocked()
	readers := p.readers
	p.readers = nil
	p.mu.Unlock()
	for _, r := range readers {
		r.mu.Lock()
		r.close()
		r.mu.Unlock()
	}
}

type pooledSource struct {
	pool *readerPool
	path string
}

func (s pooledSource) with(ctx context.Context, fn func(*reader) error) error {
	r, err := s.pool.acquire(ctx, s.path)
	if err != nil {
		return err
	}
	defer s.pool.release(s.path, r)
	return fn(r)
}

// standaloneSource owns a single reader for a Repo opened outside the
// pool — inside a Git hook, where the reader must see the hook's
// quarantined objects through the environment Git gave the hook.
type standaloneSource struct {
	gate chan struct{}
	path string
	env  []string
	r    *reader
}

func (s *standaloneSource) with(ctx context.Context, fn func(*reader) error) error {
	select {
	case s.gate <- struct{}{}:
	case <-ctx.Done():
		return ctx.Err()
	}
	defer func() { <-s.gate }()
	if s.r == nil || s.r.broken {
		if s.r != nil {
			s.r.close()
		}
		r, err := startReader(s.path, s.env)
		if err != nil {
			return err
		}
		s.r = r
	}
	return fn(s.r)
}

func (s *standaloneSource) close() {
	s.gate <- struct{}{}
	defer func() { <-s.gate }()
	if s.r != nil {
		s.r.close()
		s.r = nil
	}
}

// objectCache is a least-recently-used cache bounded by total cost, used
// for parsed objects keyed by their hash. Git objects are
// content-addressed — a hash always names the same bytes — so a cached
// entry can never go stale and needs no invalidation.
type objectCache struct {
	mu      sync.Mutex
	maxCost int64
	cost    int64
	order   *list.List
	items   map[string]*list.Element
}

type cacheEntry struct {
	key   string
	value any
	cost  int64
}

func newObjectCache(maxCost int64) *objectCache {
	return &objectCache{maxCost: maxCost, order: list.New(), items: make(map[string]*list.Element)}
}

func (c *objectCache) get(key string) (any, bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	el, ok := c.items[key]
	if !ok {
		return nil, false
	}
	c.order.MoveToFront(el)
	return el.Value.(*cacheEntry).value, true
}

func (c *objectCache) add(key string, value any, cost int64) {
	// Past this fraction, one entry would evict most of the rest of the
	// cache just to hold itself, likely only to be evicted in turn the
	// next time something else is added — worse than not caching it.
	if cost > c.maxCost/8 {
		return
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	if el, ok := c.items[key]; ok {
		c.order.MoveToFront(el)
		return
	}
	c.items[key] = c.order.PushFront(&cacheEntry{key: key, value: value, cost: cost})
	c.cost += cost
	for c.cost > c.maxCost {
		oldest := c.order.Back()
		entry := oldest.Value.(*cacheEntry)
		c.order.Remove(oldest)
		delete(c.items, entry.key)
		c.cost -= entry.cost
	}
}
